routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::view('/', 'auth.login')->middleware('guest');


Route::get('logout', 'Auth\LoginController@logout');


Route::group(['middleware' => ['auth']], function () {
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
});

/**
 * Orders
 */
Route::group(['prefix' => 'orders', 'as' => 'orders.'], function () {
    Route::get('/', 'OrderController@index')->name('index');
    Route::post('/', 'OrderController@store')->name('store');
    Route::get('/create', 'OrderController@create')->name('create');
    Route::get('/dispatch', 'OrderController@dispatchOrder')->name('dispatchOrder');
    Route::get('/sync', 'OrderController@syncOrder')->name('syncOrder');
    Route::get('/merge', 'OrderController@mergeOrder')->name('mergeOrder');
    Route::get('/{status}', 'OrderController@index')->name('index');
    Route::get('/{order}/edit', 'OrderController@edit')->name('edit');
    Route::put('/{order}', 'OrderController@update')->name('update');
    Route::delete('/{order}', 'OrderController@destroy')->name('delete');
});

resources/views/home/layouts/partials/_footer.blade.php
<!--footer-->
<footer class="footer">
    <div class="container">
        <div class="row align-items-center flex-row-reverse">
            <div class="col-lg-12 col-sm-12 text-center">
                Copyright © {{ \Carbon\Carbon::now()->year }}
                <a href="http://www.mdxsolutions.co.uk/" target="_blank">Mdx Solutions</a>.
                Designed by <a href="#">MDX</a>
                All rights reserved.
            </div>
        </div>
    </div>
</footer>
<!-- End Footer-->

resources/views/home/layouts/partials/_header.blade.php
<!--app-header-->
<div class="app-header header d-flex">
    <div class="container-fluid">
        <div class="d-flex">
            <a class="header-brand" href="{{ url('/dashboard') }}">
                {{ config('app.name', 'Shipping') }}
            </a><!-- logo-->
            <a aria-label="Hide Sidebar" class="app-sidebar__toggle" data-toggle="sidebar" href="#"></a><!-- sidebar-toggle-->

            <div class="dropdown d-none d-md-flex">
                <a  class="nav-link icon full-screen-link">
                    <i class="fe fe-maximize-2"  id="fullscreen-button"></i>
                </a>
            </div><!-- full-screen -->
            <div class="d-flex order-lg-2 ml-auto horizontal-dropdown">
                <div class="dropdown dropdown-toggle">
                   @auth
                        <a href="#" class="nav-link leading-none" data-toggle="dropdown">
                            <span class="avatar avatar-md brround"><img src="{{ asset('assets/images/faces/male/33.jpg') }}" alt="Profile-img" class="avatar avatar-md brround"></span>
                            <span class="mr-3 d-none d-lg-block ">
                                <span class="text-gray-white"><span class="ml-2">{{ Auth()->user()->name }}</span></span>
                            </span>
                        </a>
                    @endauth
                    <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                        @auth
                            <div class="text-center">
                                <a href="#" class="dropdown-item text-center font-weight-sembold user">{{ Auth()->user()->name }}</a>
                                <div class="dropdown-divider"></div>
                            </div>
                        @endauth
                        <a class="dropdown-item" href="#">
                            <i class="dropdown-icon mdi mdi-account-outline "></i> Profile
                        </a>
                        <a class="dropdown-item" href="#">
                            <i class="dropdown-icon  mdi mdi-settings"></i> Settings
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                            <i class="dropdown-icon mdi  mdi-logout-variant"></i> Sign out
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>

                    </div>
                </div><!-- profile -->
            </div>
        </div>
    </div>
</div>
<!--app-header end-->

resources/views/home/layouts/partials/_page_header.blade.php
<!-- page-header -->
<div class="page-header">
    <h4 class="page-title">@yield('title')</h4>
    <ol class="breadcrumb"><!-- breadcrumb -->
        <li class="breadcrumb-item"><a href="{{ request()->path() }}">{{ ucfirst(request()->path()) }}</a></li>
{{--        <li class="breadcrumb-item active" aria-current="page">Dashboard 1</li>--}}
    </ol><!-- End breadcrumb -->
</div>
<!-- End page-header -->

resources/views/home/layouts/partials/_sidebar.blade.php
<!-- Sidebar menu-->
<div class="app-sidebar__overlay" data-toggle="sidebar"></div>
<aside class="app-sidebar">
    <div class="app-sidebar__user">
        <div class="dropdown user-pro-body">
            <div>
                <img src="{{ asset('assets/images/faces/male/33.jpg') }}" alt="user-img" class="avatar avatar-xl brround mCS_img_loaded">
            </div>
            @auth
                <div class="user-info">
                    <h4 class="font-weight-semibold text-white mt-2 mb-1">{{ Auth::user()->name }}</h4>
                    <span class="mb-0 text-white-transparent">Mdx Solutions</span>
                </div>
            @endauth
        </div>
    </div>
    <ul class="side-menu">
        @if(Route::has('dashboard'))
        <li>
            <a class="side-menu__item {{ return_if(on_page('dashboard'), 'active') }}"
               href="{{ route('dashboard') }}">
                <i class="side-menu__icon fa fa-question-circle"></i>
                <span class="side-menu__label">Dashboard</span>
            </a>
        </li>
        @endif

        @if(Route::has('orders.index'))

            <li class="slide">
                <a
                    class="side-menu__item {{ return_if(on_page('orders.pending'), 'active')  }}"
                    data-toggle="slide"
                    href="#">
                    <i class="side-menu__icon fa fa-cubes"></i>
                    <span class="side-menu__label">Orders</span>
                    <i class="angle fa fa-angle-right"></i>
                </a>
                <ul class="slide-menu">
                    <li>
                        <a href="{{ route('orders.index', '') }}" class="slide-item">All Orders</a>
                    </li>
                    <li>
                        <a href="{{ route('orders.index', 'processing') }}" class="slide-item">Processing</a>
                    </li>
                    <li>
                        <a href="{{ route('orders.index', 'pending') }}" class="slide-item">Pending</a>
                    </li>
                    <li>
                        <a href="{{ route('orders.index', 'shipped') }}" class="slide-item">Shipped</a>
                    </li>
                    <li>
                        <a href="{{ route('orders.dispatchOrder') }}" class="slide-item">Sync Dispatch</a>
                    </li>
                    <li>
                        <a href="{{ route('orders.syncOrder') }}" class="slide-item">Sync Orders</a>
                    </li>
                    <li>
                        <a href="{{ route('orders.mergeOrder') }}" class="slide-item">Merge Orders</a>
                    </li>
                </ul>
            </li>

        @endif

    </ul>
</aside>
<!--sidemenu end-->